name: Code quality

on:
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run Biome
        run: npx @biomejs/biome@1.5.0 ci ./backend ./cdk
